[StackOp_Forwarder]
action.keyindicator.invert = 0
action.makestreams.param.verbose = 0
action.nbtstat.param.verbose = 0
action.notable.param.verbose = 0
action.nslookup.param.verbose = 0
action.ping.param.verbose = 0
action.risk.forceCsvResults = 1
action.risk.param.verbose = 0
action.script = 1
action.script.filename = stack_op_forwarder.py
action.send2uba.param.verbose = 0
action.threat_add.param.verbose = 0
action.webhook.enable_allowlist = 0
alert.digest_mode = 0
alert.suppress = 0
alert.track = 0
cron_schedule = * * * * *
dispatch.earliest_time = rt
dispatch.latest_time = rt
enableSched = 1
request.ui_dispatch_app = search
request.ui_dispatch_view = search
search = index=notable sourcetype=stash

