[Alerts]
acceleration = 0
acceleration.manual_rebuilds = 0

[Change]
acceleration = 1
acceleration.manual_rebuilds = 1

[Endpoint]
acceleration = 1
acceleration.manual_rebuilds = 1

[Web]
acceleration = 1
acceleration.manual_rebuilds = 1

[Authentication]
acceleration = True

[Certificates]
acceleration = True

[Email]
acceleration = True

[Intrusion_Detection]
acceleration = True

[Malware]
acceleration = True

[Network_Resolution]
acceleration = True

[Network_Sessions]
acceleration = True

[Network_Traffic]
acceleration = True

[Performance]
acceleration = True

[Splunk_Audit]
acceleration = True

[Ticket_Management]
acceleration = True

[Updates]
acceleration = True

[Vulnerabilities]
acceleration = True