[cim_Change_indexes]
definition = (index=windows OR index=proxy OR index=vyatta)
disabled = 0

[cim_Endpoint_indexes]
definition = (index=windows)
disabled = 0

[cim_Web_indexes]
definition = (index=proxy)
disabled = 0
