ansible_host: 10.255.240.170
network_interfaces:
  - name: "eth0"
    ipv4:
      type: "ethernet"
      address: "10.255.240.170"
      netmask: "255.255.240.0"
      gateway: ""
  - name: "eth1"
    ipv4:
      type: "ethernet"
      address: "172.16.2.20"
      netmask: "255.255.255.0"
      gateway: "172.16.2.1"
    dns:
      - "172.16.2.7"
      - "8.8.8.8"
