---
- name: restart billing
  ansible.builtin.systemd:
    name: billing
    state: restarted
    daemon_reload: true

- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
